image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - release

build:
  stage: build
  script:
    - docker build --tag registry.heroku.com/yorck-ratings/web --rm .
    - echo $HEROKU_API_KEY | docker login --username _ --password-stdin registry.heroku.com
    - docker push registry.heroku.com/yorck-ratings/web

release:
  stage: release
  script:
    - docker run --rm -e HEROKU_API_KEY=$HEROKU_API_KEY dickeyxxx/heroku-cli:v7.0.98 heroku container:release web --app yorck-ratings
