image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - release

build:
  stage: build
  script:
    - ./bin/build.sh

release:
  stage: release
  script:
    - ./bin/brelease.sh
