image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

before_script:
    - apt-get update -y

test:
  script:
    - apt-get install default-jre -y
    - wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    - chmod a+x lein
    - export LEIN_ROOT=1
    - PATH=$PATH:.
    - lein deps
    - lein midje

build:
  script:
    - ./build.sh

deploy:
  script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - ./deploy.sh
